name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.16

            - name: Install dependencies
              run: go mod tidy

            - name: Run tests
              run: go test ./scripts/...

            - name: Deploy to Azure
              if: github.ref == 'refs/heads/main'
              uses: azure/functions-action@v1
              with:
                app-name: "your-function-app-name"
                package: "."
                publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE}}